/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ihg.me2.archive.service.service.base;

import com.ihg.me2.archive.service.model.ArchiveContent;
import com.ihg.me2.archive.service.service.ArchiveContentLocalService;
import com.ihg.me2.archive.service.service.ArchiveContentService;
import com.ihg.me2.archive.service.service.persistence.ArchiveContentFinder;
import com.ihg.me2.archive.service.service.persistence.ArchiveContentPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the archive content local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ihg.me2.archive.service.service.impl.ArchiveContentLocalServiceImpl}.
 * </p>
 *
 * @author Sandip Patel
 * @see com.ihg.me2.archive.service.service.impl.ArchiveContentLocalServiceImpl
 * @see com.ihg.me2.archive.service.service.ArchiveContentLocalServiceUtil
 * @generated
 */
public abstract class ArchiveContentLocalServiceBaseImpl
	implements ArchiveContentLocalService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.ihg.me2.archive.service.service.ArchiveContentLocalServiceUtil} to access the archive content local service.
	 */

	/**
	 * Adds the archive content to the database. Also notifies the appropriate model listeners.
	 *
	 * @param archiveContent the archive content to add
	 * @return the archive content that was added
	 * @throws SystemException if a system exception occurred
	 */
	public ArchiveContent addArchiveContent(ArchiveContent archiveContent)
		throws SystemException {
		archiveContent.setNew(true);

		return archiveContentPersistence.update(archiveContent, false);
	}

	/**
	 * Creates a new archive content with the primary key. Does not add the archive content to the database.
	 *
	 * @param CONTENT_ID the primary key for the new archive content
	 * @return the new archive content
	 */
	public ArchiveContent createArchiveContent(String CONTENT_ID) {
		return archiveContentPersistence.create(CONTENT_ID);
	}

	/**
	 * Deletes the archive content with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param CONTENT_ID the primary key of the archive content to delete
	 * @throws PortalException if a archive content with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteArchiveContent(String CONTENT_ID)
		throws PortalException, SystemException {
		archiveContentPersistence.remove(CONTENT_ID);
	}

	/**
	 * Deletes the archive content from the database. Also notifies the appropriate model listeners.
	 *
	 * @param archiveContent the archive content to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteArchiveContent(ArchiveContent archiveContent)
		throws SystemException {
		archiveContentPersistence.remove(archiveContent);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return archiveContentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return archiveContentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return archiveContentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return archiveContentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the archive content with the primary key.
	 *
	 * @param CONTENT_ID the primary key of the archive content to get
	 * @return the archive content
	 * @throws PortalException if a archive content with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public ArchiveContent getArchiveContent(String CONTENT_ID)
		throws PortalException, SystemException {
		return archiveContentPersistence.findByPrimaryKey(CONTENT_ID);
	}

	/**
	 * Gets a range of all the archive contents.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of archive contents to return
	 * @param end the upper bound of the range of archive contents to return (not inclusive)
	 * @return the range of archive contents
	 * @throws SystemException if a system exception occurred
	 */
	public List<ArchiveContent> getArchiveContents(int start, int end)
		throws SystemException {
		return archiveContentPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of archive contents.
	 *
	 * @return the number of archive contents
	 * @throws SystemException if a system exception occurred
	 */
	public int getArchiveContentsCount() throws SystemException {
		return archiveContentPersistence.countAll();
	}

	/**
	 * Updates the archive content in the database. Also notifies the appropriate model listeners.
	 *
	 * @param archiveContent the archive content to update
	 * @return the archive content that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ArchiveContent updateArchiveContent(ArchiveContent archiveContent)
		throws SystemException {
		archiveContent.setNew(false);

		return archiveContentPersistence.update(archiveContent, true);
	}

	/**
	 * Updates the archive content in the database. Also notifies the appropriate model listeners.
	 *
	 * @param archiveContent the archive content to update
	 * @param merge whether to merge the archive content with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the archive content that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ArchiveContent updateArchiveContent(ArchiveContent archiveContent,
		boolean merge) throws SystemException {
		archiveContent.setNew(false);

		return archiveContentPersistence.update(archiveContent, merge);
	}

	/**
	 * Gets the archive content local service.
	 *
	 * @return the archive content local service
	 */
	public ArchiveContentLocalService getArchiveContentLocalService() {
		return archiveContentLocalService;
	}

	/**
	 * Sets the archive content local service.
	 *
	 * @param archiveContentLocalService the archive content local service
	 */
	public void setArchiveContentLocalService(
		ArchiveContentLocalService archiveContentLocalService) {
		this.archiveContentLocalService = archiveContentLocalService;
	}

	/**
	 * Gets the archive content remote service.
	 *
	 * @return the archive content remote service
	 */
	public ArchiveContentService getArchiveContentService() {
		return archiveContentService;
	}

	/**
	 * Sets the archive content remote service.
	 *
	 * @param archiveContentService the archive content remote service
	 */
	public void setArchiveContentService(
		ArchiveContentService archiveContentService) {
		this.archiveContentService = archiveContentService;
	}

	/**
	 * Gets the archive content persistence.
	 *
	 * @return the archive content persistence
	 */
	public ArchiveContentPersistence getArchiveContentPersistence() {
		return archiveContentPersistence;
	}

	/**
	 * Sets the archive content persistence.
	 *
	 * @param archiveContentPersistence the archive content persistence
	 */
	public void setArchiveContentPersistence(
		ArchiveContentPersistence archiveContentPersistence) {
		this.archiveContentPersistence = archiveContentPersistence;
	}

	/**
	 * Gets the archive content finder.
	 *
	 * @return the archive content finder
	 */
	public ArchiveContentFinder getArchiveContentFinder() {
		return archiveContentFinder;
	}

	/**
	 * Sets the archive content finder.
	 *
	 * @param archiveContentFinder the archive content finder
	 */
	public void setArchiveContentFinder(
		ArchiveContentFinder archiveContentFinder) {
		this.archiveContentFinder = archiveContentFinder;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = archiveContentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ArchiveContentLocalService.class)
	protected ArchiveContentLocalService archiveContentLocalService;
	@BeanReference(type = ArchiveContentService.class)
	protected ArchiveContentService archiveContentService;
	@BeanReference(type = ArchiveContentPersistence.class)
	protected ArchiveContentPersistence archiveContentPersistence;
	@BeanReference(type = ArchiveContentFinder.class)
	protected ArchiveContentFinder archiveContentFinder;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}