/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ihg.me2.archive.service.model.impl;

import com.ihg.me2.archive.service.model.ArchiveContent;
import com.ihg.me2.archive.service.model.ArchiveContentModel;
import com.ihg.me2.archive.service.model.ArchiveContentSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the ArchiveContent service. Represents a row in the &quot;ARCHIVAL_CONTENT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.me2.archive.service.model.ArchiveContentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArchiveContentImpl}.
 * </p>
 *
 * @author Sandip Patel
 * @see ArchiveContentImpl
 * @see com.ihg.me2.archive.service.model.ArchiveContent
 * @see com.ihg.me2.archive.service.model.ArchiveContentModel
 * @generated
 */
public class ArchiveContentModelImpl extends BaseModelImpl<ArchiveContent>
	implements ArchiveContentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a archive content model instance should use the {@link com.ihg.me2.archive.service.model.ArchiveContent} interface instead.
	 */
	public static final String TABLE_NAME = "ARCHIVAL_CONTENT";
	public static final Object[][] TABLE_COLUMNS = {
			{ "CONTENT_ID", new Integer(Types.VARCHAR) },
			{ "CONTENT_TYP", new Integer(Types.VARCHAR) },
			{ "CONTENT_NM", new Integer(Types.VARCHAR) },
			{ "GRP_ID", new Integer(Types.BIGINT) },
			{ "AUTHOR_EMAIL_ID", new Integer(Types.VARCHAR) },
			{ "AUTHOR_NM", new Integer(Types.VARCHAR) },
			{ "CONTENT_URL_TXT", new Integer(Types.VARCHAR) },
			{ "CONTENT_STAT_CD", new Integer(Types.VARCHAR) },
			{ "CONTENT_STAT_MOD_DT", new Integer(Types.TIMESTAMP) },
			{ "CONTENT_STAT_NOTIFIED_DT", new Integer(Types.TIMESTAMP) },
			{ "CONTENT_STAT_EXPIRED_DT", new Integer(Types.TIMESTAMP) },
			{ "CONTENT_STAT_DEL_DT", new Integer(Types.TIMESTAMP) },
			{ "CREAT_USR_ID", new Integer(Types.VARCHAR) },
			{ "CREAT_TS", new Integer(Types.TIMESTAMP) },
			{ "LST_UPDT_USR_ID", new Integer(Types.VARCHAR) },
			{ "LST_UPDT_TS", new Integer(Types.TIMESTAMP) }
		};
	public static final String TABLE_SQL_CREATE = "create table ARCHIVAL_CONTENT (CONTENT_ID VARCHAR(50) not null primary key,CONTENT_TYP VARCHAR(30) null,CONTENT_NM VARCHAR(200) null,GRP_ID LONG,AUTHOR_EMAIL_ID VARCHAR(100) null,AUTHOR_NM VARCHAR(30) null,CONTENT_URL_TXT VARCHAR(50) null,CONTENT_STAT_CD VARCHAR(20) null,CONTENT_STAT_MOD_DT DATE null,CONTENT_STAT_NOTIFIED_DT DATE null,CONTENT_STAT_EXPIRED_DT DATE null,CONTENT_STAT_DEL_DT DATE null,CREAT_USR_ID VARCHAR(50) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(50) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table ARCHIVAL_CONTENT";
	public static final String ORDER_BY_JPQL = " ORDER BY archiveContent.CONTENT_NM ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ARCHIVAL_CONTENT.CONTENT_NM ASC";
	public static final String DATA_SOURCE = "archiveDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "archiveTxManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.me2.archive.service.model.ArchiveContent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.me2.archive.service.model.ArchiveContent"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ArchiveContent toModel(ArchiveContentSoap soapModel) {
		ArchiveContent model = new ArchiveContentImpl();

		model.setCONTENT_ID(soapModel.getCONTENT_ID());
		model.setCONTENT_TYP(soapModel.getCONTENT_TYP());
		model.setCONTENT_NM(soapModel.getCONTENT_NM());
		model.setGRP_ID(soapModel.getGRP_ID());
		model.setAUTHOR_EMAIL_ID(soapModel.getAUTHOR_EMAIL_ID());
		model.setAUTHOR_NM(soapModel.getAUTHOR_NM());
		model.setCONTENT_URL_TXT(soapModel.getCONTENT_URL_TXT());
		model.setCONTENT_STAT_CD(soapModel.getCONTENT_STAT_CD());
		model.setCONTENT_STAT_MOD_DT(soapModel.getCONTENT_STAT_MOD_DT());
		model.setCONTENT_STAT_NOTIFIED_DT(soapModel.getCONTENT_STAT_NOTIFIED_DT());
		model.setCONTENT_STAT_EXPIRED_DT(soapModel.getCONTENT_STAT_EXPIRED_DT());
		model.setCONTENT_STAT_DEL_DT(soapModel.getCONTENT_STAT_DEL_DT());
		model.setCREAT_USR_ID(soapModel.getCREAT_USR_ID());
		model.setCREAT_TS(soapModel.getCREAT_TS());
		model.setLST_UPDT_USR_ID(soapModel.getLST_UPDT_USR_ID());
		model.setLST_UPDT_TS(soapModel.getLST_UPDT_TS());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ArchiveContent> toModels(ArchiveContentSoap[] soapModels) {
		List<ArchiveContent> models = new ArrayList<ArchiveContent>(soapModels.length);

		for (ArchiveContentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.me2.archive.service.model.ArchiveContent"));

	public ArchiveContentModelImpl() {
	}

	public String getPrimaryKey() {
		return _CONTENT_ID;
	}

	public void setPrimaryKey(String pk) {
		setCONTENT_ID(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return _CONTENT_ID;
	}

	public String getCONTENT_ID() {
		if (_CONTENT_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _CONTENT_ID;
		}
	}

	public void setCONTENT_ID(String CONTENT_ID) {
		_CONTENT_ID = CONTENT_ID;
	}

	public String getCONTENT_TYP() {
		if (_CONTENT_TYP == null) {
			return StringPool.BLANK;
		}
		else {
			return _CONTENT_TYP;
		}
	}

	public void setCONTENT_TYP(String CONTENT_TYP) {
		_CONTENT_TYP = CONTENT_TYP;
	}

	public String getCONTENT_NM() {
		if (_CONTENT_NM == null) {
			return StringPool.BLANK;
		}
		else {
			return _CONTENT_NM;
		}
	}

	public void setCONTENT_NM(String CONTENT_NM) {
		_CONTENT_NM = CONTENT_NM;
	}

	public long getGRP_ID() {
		return _GRP_ID;
	}

	public void setGRP_ID(long GRP_ID) {
		_GRP_ID = GRP_ID;
	}

	public String getAUTHOR_EMAIL_ID() {
		if (_AUTHOR_EMAIL_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _AUTHOR_EMAIL_ID;
		}
	}

	public void setAUTHOR_EMAIL_ID(String AUTHOR_EMAIL_ID) {
		_AUTHOR_EMAIL_ID = AUTHOR_EMAIL_ID;
	}

	public String getAUTHOR_NM() {
		return _AUTHOR_NM;
	}

	public void setAUTHOR_NM(String AUTHOR_NM) {
		_AUTHOR_NM = AUTHOR_NM;
	}

	public String getCONTENT_URL_TXT() {
		if (_CONTENT_URL_TXT == null) {
			return StringPool.BLANK;
		}
		else {
			return _CONTENT_URL_TXT;
		}
	}

	public void setCONTENT_URL_TXT(String CONTENT_URL_TXT) {
		_CONTENT_URL_TXT = CONTENT_URL_TXT;
	}

	public String getCONTENT_STAT_CD() {
		if (_CONTENT_STAT_CD == null) {
			return StringPool.BLANK;
		}
		else {
			return _CONTENT_STAT_CD;
		}
	}

	public void setCONTENT_STAT_CD(String CONTENT_STAT_CD) {
		_CONTENT_STAT_CD = CONTENT_STAT_CD;
	}

	public Date getCONTENT_STAT_MOD_DT() {
		return _CONTENT_STAT_MOD_DT;
	}

	public void setCONTENT_STAT_MOD_DT(Date CONTENT_STAT_MOD_DT) {
		_CONTENT_STAT_MOD_DT = CONTENT_STAT_MOD_DT;
	}

	public Date getCONTENT_STAT_NOTIFIED_DT() {
		return _CONTENT_STAT_NOTIFIED_DT;
	}

	public void setCONTENT_STAT_NOTIFIED_DT(Date CONTENT_STAT_NOTIFIED_DT) {
		_CONTENT_STAT_NOTIFIED_DT = CONTENT_STAT_NOTIFIED_DT;
	}

	public Date getCONTENT_STAT_EXPIRED_DT() {
		return _CONTENT_STAT_EXPIRED_DT;
	}

	public void setCONTENT_STAT_EXPIRED_DT(Date CONTENT_STAT_EXPIRED_DT) {
		_CONTENT_STAT_EXPIRED_DT = CONTENT_STAT_EXPIRED_DT;
	}

	public Date getCONTENT_STAT_DEL_DT() {
		return _CONTENT_STAT_DEL_DT;
	}

	public void setCONTENT_STAT_DEL_DT(Date CONTENT_STAT_DEL_DT) {
		_CONTENT_STAT_DEL_DT = CONTENT_STAT_DEL_DT;
	}

	public String getCREAT_USR_ID() {
		if (_CREAT_USR_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _CREAT_USR_ID;
		}
	}

	public void setCREAT_USR_ID(String CREAT_USR_ID) {
		_CREAT_USR_ID = CREAT_USR_ID;
	}

	public Date getCREAT_TS() {
		return _CREAT_TS;
	}

	public void setCREAT_TS(Date CREAT_TS) {
		_CREAT_TS = CREAT_TS;
	}

	public String getLST_UPDT_USR_ID() {
		if (_LST_UPDT_USR_ID == null) {
			return StringPool.BLANK;
		}
		else {
			return _LST_UPDT_USR_ID;
		}
	}

	public void setLST_UPDT_USR_ID(String LST_UPDT_USR_ID) {
		_LST_UPDT_USR_ID = LST_UPDT_USR_ID;
	}

	public Date getLST_UPDT_TS() {
		return _LST_UPDT_TS;
	}

	public void setLST_UPDT_TS(Date LST_UPDT_TS) {
		_LST_UPDT_TS = LST_UPDT_TS;
	}

	public ArchiveContent toEscapedModel() {
		if (isEscapedModel()) {
			return (ArchiveContent)this;
		}
		else {
			return (ArchiveContent)Proxy.newProxyInstance(ArchiveContent.class.getClassLoader(),
				new Class[] { ArchiveContent.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		ArchiveContentImpl clone = new ArchiveContentImpl();

		clone.setCONTENT_ID(getCONTENT_ID());
		clone.setCONTENT_TYP(getCONTENT_TYP());
		clone.setCONTENT_NM(getCONTENT_NM());
		clone.setGRP_ID(getGRP_ID());
		clone.setAUTHOR_EMAIL_ID(getAUTHOR_EMAIL_ID());
		clone.setAUTHOR_NM(getAUTHOR_NM());
		clone.setCONTENT_URL_TXT(getCONTENT_URL_TXT());
		clone.setCONTENT_STAT_CD(getCONTENT_STAT_CD());
		clone.setCONTENT_STAT_MOD_DT(getCONTENT_STAT_MOD_DT());
		clone.setCONTENT_STAT_NOTIFIED_DT(getCONTENT_STAT_NOTIFIED_DT());
		clone.setCONTENT_STAT_EXPIRED_DT(getCONTENT_STAT_EXPIRED_DT());
		clone.setCONTENT_STAT_DEL_DT(getCONTENT_STAT_DEL_DT());
		clone.setCREAT_USR_ID(getCREAT_USR_ID());
		clone.setCREAT_TS(getCREAT_TS());
		clone.setLST_UPDT_USR_ID(getLST_UPDT_USR_ID());
		clone.setLST_UPDT_TS(getLST_UPDT_TS());

		return clone;
	}

	public int compareTo(ArchiveContent archiveContent) {
		int value = 0;

		value = getCONTENT_NM().compareTo(archiveContent.getCONTENT_NM());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ArchiveContent archiveContent = null;

		try {
			archiveContent = (ArchiveContent)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String pk = archiveContent.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{CONTENT_ID=");
		sb.append(getCONTENT_ID());
		sb.append(", CONTENT_TYP=");
		sb.append(getCONTENT_TYP());
		sb.append(", CONTENT_NM=");
		sb.append(getCONTENT_NM());
		sb.append(", GRP_ID=");
		sb.append(getGRP_ID());
		sb.append(", AUTHOR_EMAIL_ID=");
		sb.append(getAUTHOR_EMAIL_ID());
		sb.append(", AUTHOR_NM=");
		sb.append(getAUTHOR_NM());
		sb.append(", CONTENT_URL_TXT=");
		sb.append(getCONTENT_URL_TXT());
		sb.append(", CONTENT_STAT_CD=");
		sb.append(getCONTENT_STAT_CD());
		sb.append(", CONTENT_STAT_MOD_DT=");
		sb.append(getCONTENT_STAT_MOD_DT());
		sb.append(", CONTENT_STAT_NOTIFIED_DT=");
		sb.append(getCONTENT_STAT_NOTIFIED_DT());
		sb.append(", CONTENT_STAT_EXPIRED_DT=");
		sb.append(getCONTENT_STAT_EXPIRED_DT());
		sb.append(", CONTENT_STAT_DEL_DT=");
		sb.append(getCONTENT_STAT_DEL_DT());
		sb.append(", CREAT_USR_ID=");
		sb.append(getCREAT_USR_ID());
		sb.append(", CREAT_TS=");
		sb.append(getCREAT_TS());
		sb.append(", LST_UPDT_USR_ID=");
		sb.append(getLST_UPDT_USR_ID());
		sb.append(", LST_UPDT_TS=");
		sb.append(getLST_UPDT_TS());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("com.ihg.me2.archive.service.model.ArchiveContent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>CONTENT_ID</column-name><column-value><![CDATA[");
		sb.append(getCONTENT_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CONTENT_TYP</column-name><column-value><![CDATA[");
		sb.append(getCONTENT_TYP());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CONTENT_NM</column-name><column-value><![CDATA[");
		sb.append(getCONTENT_NM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>GRP_ID</column-name><column-value><![CDATA[");
		sb.append(getGRP_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AUTHOR_EMAIL_ID</column-name><column-value><![CDATA[");
		sb.append(getAUTHOR_EMAIL_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AUTHOR_NM</column-name><column-value><![CDATA[");
		sb.append(getAUTHOR_NM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CONTENT_URL_TXT</column-name><column-value><![CDATA[");
		sb.append(getCONTENT_URL_TXT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CONTENT_STAT_CD</column-name><column-value><![CDATA[");
		sb.append(getCONTENT_STAT_CD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CONTENT_STAT_MOD_DT</column-name><column-value><![CDATA[");
		sb.append(getCONTENT_STAT_MOD_DT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CONTENT_STAT_NOTIFIED_DT</column-name><column-value><![CDATA[");
		sb.append(getCONTENT_STAT_NOTIFIED_DT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CONTENT_STAT_EXPIRED_DT</column-name><column-value><![CDATA[");
		sb.append(getCONTENT_STAT_EXPIRED_DT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CONTENT_STAT_DEL_DT</column-name><column-value><![CDATA[");
		sb.append(getCONTENT_STAT_DEL_DT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CREAT_USR_ID</column-name><column-value><![CDATA[");
		sb.append(getCREAT_USR_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CREAT_TS</column-name><column-value><![CDATA[");
		sb.append(getCREAT_TS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LST_UPDT_USR_ID</column-name><column-value><![CDATA[");
		sb.append(getLST_UPDT_USR_ID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LST_UPDT_TS</column-name><column-value><![CDATA[");
		sb.append(getLST_UPDT_TS());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _CONTENT_ID;
	private String _CONTENT_TYP;
	private String _CONTENT_NM;
	private long _GRP_ID;
	private String _AUTHOR_EMAIL_ID;
	private String _AUTHOR_NM;
	private String _CONTENT_URL_TXT;
	private String _CONTENT_STAT_CD;
	private Date _CONTENT_STAT_MOD_DT;
	private Date _CONTENT_STAT_NOTIFIED_DT;
	private Date _CONTENT_STAT_EXPIRED_DT;
	private Date _CONTENT_STAT_DEL_DT;
	private String _CREAT_USR_ID;
	private Date _CREAT_TS;
	private String _LST_UPDT_USR_ID;
	private Date _LST_UPDT_TS;
}